var WORD_DATA = WORD_DATA || {};
WORD_DATA['es'] = {
  categories: {
    saludos: '问候 Saludos', comida: '食物 Comida', viaje: '旅行 Viaje',
    numeros: '数字 Números', familia: '家庭 Familia', colores: '颜色 Colores',
    cuerpo: '身体 Cuerpo', clima: '天气 Clima', diario: '日常 Diario', emociones: '情感 Emociones'
  },
  words: [
    // ===== saludos (问候) =====
    {word:'hola',meaning:'你好',phonetic:'/ˈo.la/',category:'saludos',difficulty:1},
    {word:'adiós',meaning:'再见',phonetic:'/a.ˈðjos/',category:'saludos',difficulty:1},
    {word:'buenos días',meaning:'早上好',phonetic:'/ˈbwe.nos ˈdi.as/',category:'saludos',difficulty:2},
    {word:'buenas tardes',meaning:'下午好',phonetic:'/ˈbwe.nas ˈtar.ðes/',category:'saludos',difficulty:2},
    {word:'buenas noches',meaning:'晚上好',phonetic:'/ˈbwe.nas ˈno.tʃes/',category:'saludos',difficulty:2},
    {word:'¿qué tal?',meaning:'你好吗？',phonetic:'/ke ˈtal/',category:'saludos',difficulty:2},
    {word:'por favor',meaning:'请',phonetic:'/poɾ fa.ˈβoɾ/',category:'saludos',difficulty:1},
    {word:'gracias',meaning:'谢谢',phonetic:'/ˈɡɾa.θjas/',category:'saludos',difficulty:1},
    {word:'de nada',meaning:'不客气',phonetic:'/de ˈna.ða/',category:'saludos',difficulty:1},
    {word:'perdón',meaning:'对不起',phonetic:'/peɾ.ˈðon/',category:'saludos',difficulty:1},
    {word:'disculpe',meaning:'打扰一下',phonetic:'/dis.ˈkul.pe/',category:'saludos',difficulty:2},
    {word:'señor',meaning:'先生',phonetic:'/se.ˈɲoɾ/',category:'saludos',difficulty:1},
    {word:'señora',meaning:'女士',phonetic:'/se.ˈɲo.ɾa/',category:'saludos',difficulty:1},
    {word:'señorita',meaning:'小姐',phonetic:'/se.ɲo.ˈɾi.ta/',category:'saludos',difficulty:2},
    {word:'bienvenido',meaning:'欢迎',phonetic:'/bjem.be.ˈni.ðo/',category:'saludos',difficulty:2},
    {word:'bienvenida',meaning:'欢迎（女）',phonetic:'/bjem.be.ˈni.ðja/',category:'saludos',difficulty:2},
    {word:'encantado',meaning:'很高兴认识你',phonetic:'/eŋ.kan.ˈta.ðo/',category:'saludos',difficulty:2},
    {word:'mucho gusto',meaning:'很高兴见到你',phonetic:'/ˈmu.tʃo ˈɡus.to/',category:'saludos',difficulty:2},
    {word:'¿cómo estás?',meaning:'你好吗？',phonetic:'/ˈko.mo es.ˈtas/',category:'saludos',difficulty:2},
    {word:'hasta luego',meaning:'回头见',phonetic:'/ˈas.ta ˈlwe.ɣo/',category:'saludos',difficulty:2},
    {word:'hasta mañana',meaning:'明天见',phonetic:'/ˈas.ta ma.ˈɲa.na/',category:'saludos',difficulty:2},
    {word:'hasta pronto',meaning:'很快再见',phonetic:'/ˈas.ta ˈpɾon.to/',category:'saludos',difficulty:2},
    {word:'chao',meaning:'再见（口语）',phonetic:'/ˈtʃao/',category:'saludos',difficulty:1},
    {word:'saludos',meaning:'问候',phonetic:'/sa.ˈlu.ðos/',category:'saludos',difficulty:2},
    {word:'bien',meaning:'好',phonetic:'/ˈbjen/',category:'saludos',difficulty:1},
    {word:'mal',meaning:'不好',phonetic:'/ˈmal/',category:'saludos',difficulty:1},
    {word:'regular',meaning:'一般',phonetic:'/re.ˈɣu.laɾ/',category:'saludos',difficulty:2},
    {word:'igualmente',meaning:'同样地',phonetic:'/i.ɣwal.ˈmen.te/',category:'saludos',difficulty:2},
    {word:'¿cómo te va?',meaning:'你过得怎样？',phonetic:'/ˈko.mo te ˈba/',category:'saludos',difficulty:2},
    {word:'nos vemos',meaning:'我们再见',phonetic:'/nos ˈbe.mos/',category:'saludos',difficulty:1},

    // ===== comida (食物) =====
    {word:'agua',meaning:'水',phonetic:'/ˈa.ɣwa/',category:'comida',difficulty:1},
    {word:'pan',meaning:'面包',phonetic:'/ˈpan/',category:'comida',difficulty:1},
    {word:'arroz',meaning:'米饭',phonetic:'/a.ˈroθ/',category:'comida',difficulty:1},
    {word:'pollo',meaning:'鸡肉',phonetic:'/ˈpo.ʎo/',category:'comida',difficulty:1},
    {word:'carne',meaning:'肉',phonetic:'/ˈkaɾ.ne/',category:'comida',difficulty:1},
    {word:'pescado',meaning:'鱼',phonetic:'/pes.ˈka.ðo/',category:'comida',difficulty:2},
    {word:'leche',meaning:'牛奶',phonetic:'/ˈle.tʃe/',category:'comida',difficulty:1},
    {word:'queso',meaning:'奶酪',phonetic:'/ˈke.so/',category:'comida',difficulty:1},
    {word:'huevo',meaning:'鸡蛋',phonetic:'/ˈwe.βo/',category:'comida',difficulty:1},
    {word:'manzana',meaning:'苹果',phonetic:'/man.ˈsa.na/',category:'comida',difficulty:2},
    {word:'plátano',meaning:'香蕉',phonetic:'/ˈpla.ta.no/',category:'comida',difficulty:2},
    {word:'naranja',meaning:'橙子',phonetic:'/na.ˈɾaŋ.xa/',category:'comida',difficulty:2},
    {word:'tomate',meaning:'番茄',phonetic:'/to.ˈma.te/',category:'comida',difficulty:1},
    {word:'cebolla',meaning:'洋葱',phonetic:'/se.ˈβo.ʎa/',category:'comida',difficulty:2},
    {word:'patata',meaning:'土豆',phonetic:'/pa.ˈta.ta/',category:'comida',difficulty:2},
    {word:'ensalada',meaning:'沙拉',phonetic:'/en.sa.ˈla.ða/',category:'comida',difficulty:2},
    {word:'sopa',meaning:'汤',phonetic:'/ˈso.pa/',category:'comida',difficulty:1},
    {word:'café',meaning:'咖啡',phonetic:'/ka.ˈfe/',category:'comida',difficulty:1},
    {word:'té',meaning:'茶',phonetic:'/ˈte/',category:'comida',difficulty:1},
    {word:'cerveza',meaning:'啤酒',phonetic:'/θeɾ.ˈβe.θa/',category:'comida',difficulty:2},
    {word:'vino',meaning:'葡萄酒',phonetic:'/ˈbi.no/',category:'comida',difficulty:1},
    {word:'azúcar',meaning:'糖',phonetic:'/a.ˈsu.kaɾ/',category:'comida',difficulty:2},
    {word:'sal',meaning:'盐',phonetic:'/ˈsal/',category:'comida',difficulty:1},
    {word:'aceite',meaning:'油',phonetic:'/a.ˈsei.te/',category:'comida',difficulty:2},
    {word:'harina',meaning:'面粉',phonetic:'/a.ˈɾi.na/',category:'comida',difficulty:2},
    {word:'jamón',meaning:'火腿',phonetic:'/xa.ˈmon/',category:'comida',difficulty:2},
    {word:'paella',meaning:'西班牙海鲜饭',phonetic:'/pa.ˈe.ʎa/',category:'comida',difficulty:2},
    {word:'tortilla',meaning:'玉米饼/蛋饼',phonetic:'/toɾ.ˈti.ʎa/',category:'comida',difficulty:2},
    {word:'postre',meaning:'甜点',phonetic:'/ˈpos.tɾe/',category:'comida',difficulty:2},
    {word:'desayuno',meaning:'早餐',phonetic:'/de.sa.ˈju.no/',category:'comida',difficulty:2},
    {word:'almuerzo',meaning:'午餐',phonetic:'/al.ˈmweɾ.θo/',category:'comida',difficulty:2},
    {word:'cena',meaning:'晚餐',phonetic:'/ˈθe.na/',category:'comida',difficulty:1},
    {word:'fruta',meaning:'水果',phonetic:'/ˈfɾu.ta/',category:'comida',difficulty:1},
    {word:'verduras',meaning:'蔬菜',phonetic:'/ˈbeɾ.ðu.ɾas/',category:'comida',difficulty:2},
    {word:'helado',meaning:'冰淇淋',phonetic:'/e.ˈla.ðo/',category:'comida',difficulty:2},
    {word:'galleta',meaning:'饼干',phonetic:'/ga.ˈʎe.ta/',category:'comida',difficulty:2},
    {word:'chocolate',meaning:'巧克力',phonetic:'/tʃo.ko.ˈla.te/',category:'comida',difficulty:2},
    {word:'limón',meaning:'柠檬',phonetic:'/li.ˈmon/',category:'comida',difficulty:1},
    {word:'fresa',meaning:'草莓',phonetic:'/ˈfɾe.sa/',category:'comida',difficulty:1},
    {word:'uva',meaning:'葡萄',phonetic:'/ˈu.ba/',category:'comida',difficulty:1},

    // ===== viaje (旅行) =====
    {word:'avión',meaning:'飞机',phonetic:'/a.ˈbjon/',category:'viaje',difficulty:2},
    {word:'tren',meaning:'火车',phonetic:'/ˈtɾen/',category:'viaje',difficulty:1},
    {word:'autobús',meaning:'公交车',phonetic:'/aw.to.ˈβus/',category:'viaje',difficulty:2},
    {word:'coche',meaning:'汽车',phonetic:'/ˈko.tʃe/',category:'viaje',difficulty:1},
    {word:'barco',meaning:'船',phonetic:'/ˈbaɾ.ko/',category:'viaje',difficulty:1},
    {word:'aeropuerto',meaning:'机场',phonetic:'/a.e.ɾo.ˈpweɾ.to/',category:'viaje',difficulty:3},
    {word:'estación',meaning:'车站',phonetic:'/es.ta.ˈθjon/',category:'viaje',difficulty:2},
    {word:'hotel',meaning:'酒店',phonetic:'/o.ˈtel/',category:'viaje',difficulty:1},
    {word:'habitación',meaning:'房间',phonetic:'/a.bi.ta.ˈθjon/',category:'viaje',difficulty:2},
    {word:'maleta',meaning:'行李箱',phonetic:'/ma.ˈle.ta/',category:'viaje',difficulty:2},
    {word:'pasaporte',meaning:'护照',phonetic:'/pa.sa.ˈpoɾ.te/',category:'viaje',difficulty:2},
    {word:'billete',meaning:'票',phonetic:'/bi.ˈʎe.te/',category:'viaje',difficulty:2},
    {word:'mapa',meaning:'地图',phonetic:'/ˈma.pa/',category:'viaje',difficulty:1},
    {word:'playa',meaning:'海滩',phonetic:'/ˈpla.ʎa/',category:'viaje',difficulty:1},
    {word:'montaña',meaning:'山',phonetic:'/mon.ˈta.ɲa/',category:'viaje',difficulty:2},
    {word:'ciudad',meaning:'城市',phonetic:'/θju.ˈðað/',category:'viaje',difficulty:2},
    {word:'país',meaning:'国家',phonetic:'/pa.ˈis/',category:'viaje',difficulty:1},
    {word:'viaje',meaning:'旅行',phonetic:'/ˈbja.xe/',category:'viaje',difficulty:1},
    {word:'turista',meaning:'游客',phonetic:'/tu.ˈɾis.ta/',category:'viaje',difficulty:2},
    {word:'equipaje',meaning:'行李',phonetic:'/e.ki.ˈpa.xe/',category:'viaje',difficulty:2},
    {word:'llegada',meaning:'到达',phonetic:'/ʎe.ˈɣa.ða/',category:'viaje',difficulty:2},
    {word:'salida',meaning:'出发',phonetic:'/sa.ˈli.ða/',category:'viaje',difficulty:2},
    {word:'destino',meaning:'目的地',phonetic:'/des.ˈti.no/',category:'viaje',difficulty:2},
    {word:'reservación',meaning:'预订',phonetic:'/re.seɾ.βa.ˈθjon/',category:'viaje',difficulty:3},
    {word:'pasajero',meaning:'乘客',phonetic:'/pa.sa.ˈxe.ɾo/',category:'viaje',difficulty:2},
    {word:'mercado',meaning:'市场',phonetic:'/meɾ.ˈka.ðo/',category:'viaje',difficulty:2},
    {word:'museo',meaning:'博物馆',phonetic:'/mu.ˈse.o/',category:'viaje',difficulty:2},
    {word:'restaurante',meaning:'餐厅',phonetic:'/res.taw.ˈɾan.te/',category:'viaje',difficulty:3},
    {word:'itinerario',meaning:'行程表',phonetic:'/i.ti.ne.ˈɾa.rjo/',category:'viaje',difficulty:3},

    // ===== números (数字) =====
    {word:'uno',meaning:'一',phonetic:'/ˈu.no/',category:'numeros',difficulty:1},
    {word:'dos',meaning:'二',phonetic:'/ˈdos/',category:'numeros',difficulty:1},
    {word:'tres',meaning:'三',phonetic:'/ˈtɾes/',category:'numeros',difficulty:1},
    {word:'cuatro',meaning:'四',phonetic:'/ˈkwa.tɾo/',category:'numeros',difficulty:1},
    {word:'cinco',meaning:'五',phonetic:'/ˈθin.ko/',category:'numeros',difficulty:1},
    {word:'seis',meaning:'六',phonetic:'/ˈsejs/',category:'numeros',difficulty:1},
    {word:'siete',meaning:'七',phonetic:'/ˈsje.te/',category:'numeros',difficulty:1},
    {word:'ocho',meaning:'八',phonetic:'/ˈo.tʃo/',category:'numeros',difficulty:1},
    {word:'nueve',meaning:'九',phonetic:'/ˈnwe.βe/',category:'numeros',difficulty:2},
    {word:'diez',meaning:'十',phonetic:'/ˈdjeθ/',category:'numeros',difficulty:1},
    {word:'veinte',meaning:'二十',phonetic:'/ˈbejn.te/',category:'numeros',difficulty:1},
    {word:'treinta',meaning:'三十',phonetic:'/ˈtɾejn.ta/',category:'numeros',difficulty:2},
    {word:'cuarenta',meaning:'四十',phonetic:'/kwa.ˈɾen.ta/',category:'numeros',difficulty:2},
    {word:'cincuenta',meaning:'五十',phonetic:'/θin.ˈkwen.ta/',category:'numeros',difficulty:2},
    {word:'sesenta',meaning:'六十',phonetic:'/se.ˈsen.ta/',category:'numeros',difficulty:2},
    {word:'setenta',meaning:'七十',phonetic:'/se.ˈten.ta/',category:'numeros',difficulty:2},
    {word:'ochenta',meaning:'八十',phonetic:'/o.ˈtʃen.ta/',category:'numeros',difficulty:2},
    {word:'noventa',meaning:'九十',phonetic:'/no.ˈβen.ta/',category:'numeros',difficulty:2},
    {word:'cien',meaning:'一百',phonetic:'/ˈθjen/',category:'numeros',difficulty:1},
    {word:'mil',meaning:'一千',phonetic:'/ˈmil/',category:'numeros',difficulty:1},
    {word:'millón',meaning:'百万',phonetic:'/mi.ˈʎon/',category:'numeros',difficulty:2},
    {word:'primero',meaning:'第一',phonetic:'/pɾi.ˈme.ɾo/',category:'numeros',difficulty:2},
    {word:'segundo',meaning:'第二',phonetic:'/se.ˈɣun.do/',category:'numeros',difficulty:2},
    {word:'tercero',meaning:'第三',phonetic:'/teɾ.ˈθe.ɾo/',category:'numeros',difficulty:2},
    {word:'doble',meaning:'双倍',phonetic:'/ˈdo.ble/',category:'numeros',difficulty:1},
    {word:'triple',meaning:'三倍',phonetic:'/ˈtɾi.ple/',category:'numeros',difficulty:2},
    {word:'la mitad',meaning:'一半',phonetic:'/la mi.ˈtað/',category:'numeros',difficulty:2},
    {word:'docena',meaning:'一打',phonetic:'/do.ˈθe.na/',category:'numeros',difficulty:2},
    {word:'cero',meaning:'零',phonetic:'/ˈθe.ɾo/',category:'numeros',difficulty:1},
    {word:'miles',meaning:'数千',phonetic:'/ˈmi.les/',category:'numeros',difficulty:1},

    // ===== familia (家庭) =====
    {word:'madre',meaning:'母亲',phonetic:'/ˈma.ðɾe/',category:'familia',difficulty:1},
    {word:'padre',meaning:'父亲',phonetic:'/ˈpa.ðɾe/',category:'familia',difficulty:1},
    {word:'hermano',meaning:'兄弟',phonetic:'/eɾ.ˈma.no/',category:'familia',difficulty:1},
    {word:'hermana',meaning:'姐妹',phonetic:'/eɾ.ˈma.na/',category:'familia',difficulty:1},
    {word:'hijo',meaning:'儿子',phonetic:'/ˈi.xo/',category:'familia',difficulty:1},
    {word:'hija',meaning:'女儿',phonetic:'/ˈi.xa/',category:'familia',difficulty:1},
    {word:'abuelo',meaning:'爷爷/外公',phonetic:'/a.ˈbwe.lo/',category:'familia',difficulty:2},
    {word:'abuela',meaning:'奶奶/外婆',phonetic:'/a.ˈbwe.la/',category:'familia',difficulty:2},
    {word:'tío',meaning:'叔叔',phonetic:'/ˈti.o/',category:'familia',difficulty:1},
    {word:'tía',meaning:'阿姨',phonetic:'/ˈti.a/',category:'familia',difficulty:1},
    {word:'primo',meaning:'表兄弟',phonetic:'/ˈpɾi.mo/',category:'familia',difficulty:1},
    {word:'prima',meaning:'表姐妹',phonetic:'/ˈpɾi.ma/',category:'familia',difficulty:1},
    {word:'esposo',meaning:'丈夫',phonetic:'/es.ˈpo.so/',category:'familia',difficulty:2},
    {word:'esposa',meaning:'妻子',phonetic:'/es.ˈpo.sa/',category:'familia',difficulty:2},
    {word:'marido',meaning:'丈夫',phonetic:'/ma.ˈɾi.ðo/',category:'familia',difficulty:2},
    {word:'mujer',meaning:'妻子/女人',phonetic:'/mu.ˈxeɾ/',category:'familia',difficulty:2},
    {word:'niño',meaning:'男孩',phonetic:'/ˈni.ɲo/',category:'familia',difficulty:1},
    {word:'niña',meaning:'女孩',phonetic:'/ˈni.ɲa/',category:'familia',difficulty:1},
    {word:'bebé',meaning:'婴儿',phonetic:'/be.ˈβe/',category:'familia',difficulty:1},
    {word:'sobrino',meaning:'侄子',phonetic:'/so.ˈbɾi.no/',category:'familia',difficulty:2},
    {word:'sobrina',meaning:'侄女',phonetic:'/so.ˈbɾi.na/',category:'familia',difficulty:2},
    {word:'cuñado',meaning:'姐夫/妹夫',phonetic:'/ku.ˈɲa.ðo/',category:'familia',difficulty:2},
    {word:'suegro',meaning:'岳父/公公',phonetic:'/ˈswe.ɣɾo/',category:'familia',difficulty:2},
    {word:'suegra',meaning:'岳母/婆婆',phonetic:'/ˈswe.ɣɾa/',category:'familia',difficulty:2},
    {word:'familia',meaning:'家庭',phonetic:'/fa.ˈmi.lja/',category:'familia',difficulty:2},
    {word:'padres',meaning:'父母',phonetic:'/ˈpa.ðɾes/',category:'familia',difficulty:1},
    {word:'hijos',meaning:'孩子们',phonetic:'/ˈi.xos/',category:'familia',difficulty:1},
    {word:'nieto',meaning:'孙子',phonetic:'/ˈnje.to/',category:'familia',difficulty:2},
    {word:'nieta',meaning:'孙女',phonetic:'/ˈnje.ta/',category:'familia',difficulty:2},
    {word:'gemelos',meaning:'双胞胎',phonetic:'/xe.ˈme.los/',category:'familia',difficulty:2},

    // ===== colores (颜色) =====
    {word:'rojo',meaning:'红色',phonetic:'/ˈro.xo/',category:'colores',difficulty:1},
    {word:'azul',meaning:'蓝色',phonetic:'/a.ˈθul/',category:'colores',difficulty:1},
    {word:'verde',meaning:'绿色',phonetic:'/ˈbeɾ.ðe/',category:'colores',difficulty:1},
    {word:'amarillo',meaning:'黄色',phonetic:'/a.ma.ˈɾi.ʎo/',category:'colores',difficulty:2},
    {word:'blanco',meaning:'白色',phonetic:'/ˈblaŋ.ko/',category:'colores',difficulty:1},
    {word:'negro',meaning:'黑色',phonetic:'/ˈne.ɣɾo/',category:'colores',difficulty:1},
    {word:'naranja',meaning:'橙色',phonetic:'/na.ˈɾaŋ.xa/',category:'colores',difficulty:2},
    {word:'rosado',meaning:'粉色',phonetic:'/ro.ˈsa.ðo/',category:'colores',difficulty:2},
    {word:'morado',meaning:'紫色',phonetic:'/mo.ˈɾa.ðo/',category:'colores',difficulty:2},
    {word:'marrón',meaning:'棕色',phonetic:'/ma.ˈrron/',category:'colores',difficulty:2},
    {word:'gris',meaning:'灰色',phonetic:'/ˈɡɾis/',category:'colores',difficulty:1},
    {word:'dorado',meaning:'金色',phonetic:'/do.ˈɾa.ðo/',category:'colores',difficulty:2},
    {word:'plateado',meaning:'银色',phonetic:'/pla.te.ˈa.ðo/',category:'colores',difficulty:3},
    {word:'celeste',meaning:'天蓝色',phonetic:'/θe.ˈles.te/',category:'colores',difficulty:2},
    {word:'turquesa',meaning:'绿松石色',phonetic:'/tuɾ.ˈke.sa/',category:'colores',difficulty:2},
    {word:'violeta',meaning:'紫罗兰色',phonetic:'/bjo.ˈle.ta/',category:'colores',difficulty:2},
    {word:'oscuro',meaning:'深的',phonetic:'/os.ˈku.ɾo/',category:'colores',difficulty:2},
    {word:'claro',meaning:'浅的',phonetic:'/ˈkla.ɾo/',category:'colores',difficulty:1},
    {word:'brillante',meaning:'闪亮的',phonetic:'/bri.ˈʎan.te/',category:'colores',difficulty:2},
    {word:'color',meaning:'颜色',phonetic:'/ko.ˈloɾ/',category:'colores',difficulty:1},
    {word:'colores',meaning:'颜色（复数）',phonetic:'/ko.ˈlo.ɾes/',category:'colores',difficulty:2},
    {word:'claro',meaning:'浅色的',phonetic:'/ˈkla.ɾo/',category:'colores',difficulty:1},
    {word:'transparente',meaning:'透明的',phonetic:'/tɾans.pa.ˈɾen.te/',category:'colores',difficulty:3},
    {word:'beige',meaning:'米色',phonetic:'/ˈbej.xe/',category:'colores',difficulty:2},
    {word:'colorido',meaning:'色彩鲜艳的',phonetic:'/ko.lo.ˈɾi.ðo/',category:'colores',difficulty:3},
    {word:'pálido',meaning:'苍白的',phonetic:'/ˈpa.li.ðo/',category:'colores',difficulty:2},
    {word:'vivo',meaning:'鲜艳的',phonetic:'/ˈbi.βo/',category:'colores',difficulty:1},
    {word:'pastel',meaning:'柔和色',phonetic:'/pas.ˈtel/',category:'colores',difficulty:2},
    {word:'árngano',meaning:'紫色',phonetic:'/ˈpuɾ.pu.ɾa/',category:'colores',difficulty:2},
    {word:'púrpura',meaning:'紫红色',phonetic:'/ˈpuɾ.pu.ɾa/',category:'colores',difficulty:2},

    // ===== cuerpo (身体) =====
    {word:'cabeza',meaning:'头',phonetic:'/ka.ˈβe.θa/',category:'cuerpo',difficulty:2},
    {word:'ojo',meaning:'眼睛',phonetic:'/ˈo.xo/',category:'cuerpo',difficulty:1},
    {word:'ojos',meaning:'眼睛（复数）',phonetic:'/ˈo.xos/',category:'cuerpo',difficulty:1},
    {word:'nariz',meaning:'鼻子',phonetic:'/na.ˈɾiθ/',category:'cuerpo',difficulty:1},
    {word:'boca',meaning:'嘴巴',phonetic:'/ˈbo.ka/',category:'cuerpo',difficulty:1},
    {word:'oreja',meaning:'耳朵',phonetic:'/o.ˈɾe.xa/',category:'cuerpo',difficulty:2},
    {word:'diente',meaning:'牙齿',phonetic:'/ˈdjen.te/',category:'cuerpo',difficulty:2},
    {word:'lengua',meaning:'舌头',phonetic:'/ˈleŋ.ɡwa/',category:'cuerpo',difficulty:2},
    {word:'mano',meaning:'手',phonetic:'/ˈma.no/',category:'cuerpo',difficulty:1},
    {word:'brazo',meaning:'手臂',phonetic:'/ˈbɾa.θo/',category:'cuerpo',difficulty:1},
    {word:'pie',meaning:'脚',phonetic:'/ˈpje/',category:'cuerpo',difficulty:1},
    {word:'pierna',meaning:'腿',phonetic:'/ˈpjeɾ.na/',category:'cuerpo',difficulty:2},
    {word:'rodilla',meaning:'膝盖',phonetic:'/ro.ˈði.ʎa/',category:'cuerpo',difficulty:2},
    {word:'corazón',meaning:'心脏',phonetic:'/ko.ra.ˈθon/',category:'cuerpo',difficulty:2},
    {word:'estómago',meaning:'胃',phonetic:'/es.ˈto.ma.ɣo/',category:'cuerpo',difficulty:2},
    {word:'espalda',meaning:'背',phonetic:'/es.ˈpal.da/',category:'cuerpo',difficulty:2},
    {word:'cuello',meaning:'脖子',phonetic:'/ˈkwe.ʎo/',category:'cuerpo',difficulty:2},
    {word:'hombro',meaning:'肩膀',phonetic:'/ˈom.bɾo/',category:'cuerpo',difficulty:2},
    {word:'dedo',meaning:'手指',phonetic:'/ˈde.ðo/',category:'cuerpo',difficulty:1},
    {word:'pelo',meaning:'头发',phonetic:'/ˈpe.lo/',category:'cuerpo',difficulty:1},
    {word:'uña',meaning:'指甲',phonetic:'/ˈu.ɲa/',category:'cuerpo',difficulty:1},
    {word:'pecho',meaning:'胸部',phonetic:'/ˈpe.tʃo/',category:'cuerpo',difficulty:1},
    {word:'cintura',meaning:'腰部',phonetic:'/sin.ˈtu.ɾa/',category:'cuerpo',difficulty:2},
    {word:'cadera',meaning:'臀部',phonetic:'/ka.ˈðe.ɾa/',category:'cuerpo',difficulty:2},
    {word:'tobillo',meaning:'脚踝',phonetic:'/to.ˈbi.ʎo/',category:'cuerpo',difficulty:2},
    {word:'codo',meaning:'手肘',phonetic:'/ˈko.ðo/',category:'cuerpo',difficulty:1},
    {word:'muñeca',meaning:'手腕',phonetic:'/mu.ˈɲe.ka/',category:'cuerpo',difficulty:2},
    {word:'cerebro',meaning:'大脑',phonetic:'/θe.ˈɾe.βɾo/',category:'cuerpo',difficulty:2},
    {word:'hueso',meaning:'骨头',phonetic:'/ˈwe.so/',category:'cuerpo',difficulty:1},
    {word:'sangre',meaning:'血液',phonetic:'/ˈsaŋ.ɡɾe/',category:'cuerpo',difficulty:2},

    // ===== clima (天气) =====
    {word:'sol',meaning:'太阳',phonetic:'/ˈsol/',category:'clima',difficulty:1},
    {word:'lluvia',meaning:'雨',phonetic:'/ˈʎu.bja/',category:'clima',difficulty:2},
    {word:'nieve',meaning:'雪',phonetic:'/ˈnje.βe/',category:'clima',difficulty:2},
    {word:'viento',meaning:'风',phonetic:'/ˈbjen.to/',category:'clima',difficulty:2},
    {word:'nube',meaning:'云',phonetic:'/ˈnu.be/',category:'clima',difficulty:1},
    {word:'tormenta',meaning:'暴风雨',phonetic:'/toɾ.ˈmen.ta/',category:'clima',difficulty:2},
    {word:'trueno',meaning:'雷声',phonetic:'/ˈtɾwe.no/',category:'clima',difficulty:2},
    {word:'relámpago',meaning:'闪电',phonetic:'/re.ˈlam.pa.ɣo/',category:'clima',difficulty:3},
    {word:'calor',meaning:'热',phonetic:'/ka.ˈloɾ/',category:'clima',difficulty:1},
    {word:'frío',meaning:'冷',phonetic:'/ˈfɾi.o/',category:'clima',difficulty:1},
    {word:'temperatura',meaning:'温度',phonetic:'/tem.pe.ra.ˈtu.ɾa/',category:'clima',difficulty:3},
    {word:'húmedo',meaning:'潮湿的',phonetic:'/ˈu.me.ðo/',category:'clima',difficulty:2},
    {word:'seco',meaning:'干燥的',phonetic:'/ˈse.ko/',category:'clima',difficulty:1},
    {word:'niebla',meaning:'雾',phonetic:'/ˈnje.βla/',category:'clima',difficulty:2},
    {word:'arcoíris',meaning:'彩虹',phonetic:'/ˈaɾ.ko.i.ɾis/',category:'clima',difficulty:3},
    {word:'huracán',meaning:'飓风',phonetic:'/u.ɾa.ˈkan/',category:'clima',difficulty:3},
    {word:'terremoto',meaning:'地震',phonetic:'/te.re.ˈmo.te/',category:'clima',difficulty:3},
    {word:'inundación',meaning:'洪水',phonetic:'/in.un.da.ˈθjon/',category:'clima',difficulty:3},
    {word:'clima',meaning:'气候',phonetic:'/ˈkli.ma/',category:'clima',difficulty:1},
    {word:'tiempo',meaning:'天气',phonetic:'/ˈtjem.po/',category:'clima',difficulty:1},
    {word:'brisa',meaning:'微风',phonetic:'/ˈbɾi.sa/',category:'clima',difficulty:2},
    {word:'helada',meaning:'霜冻',phonetic:'/e.ˈla.ða/',category:'clima',difficulty:2},
    {word:'granizo',meaning:'冰雹',phonetic:'/ɡɾa.ˈni.θo/',category:'clima',difficulty:2},
    {word:'soleado',meaning:'晴朗的',phonetic:'/so.le.ˈa.ðo/',category:'clima',difficulty:2},
    {word:'nublado',meaning:'多云的',phonetic:'/nu.ˈbla.ðo/',category:'clima',difficulty:2},
    {word:'lluvioso',meaning:'多雨的',phonetic:'/ʎu.ˈbjo.so/',category:'clima',difficulty:2},
    {word:'nevado',meaning:'下雪的',phonetic:'/ne.ˈβa.ðo/',category:'clima',difficulty:2},
    {word:'ventoso',meaning:'有风的',phonetic:'/ben.ˈto.so/',category:'clima',difficulty:2},
    {word:'primavera',meaning:'春天',phonetic:'/pɾi.ma.ˈβe.ɾa/',category:'clima',difficulty:3},

    // ===== diario (日常) =====
    {word:'casa',meaning:'房子',phonetic:'/ˈka.sa/',category:'diario',difficulty:1},
    {word:'escuela',meaning:'学校',phonetic:'/es.ˈkwe.la/',category:'diario',difficulty:2},
    {word:'trabajo',meaning:'工作',phonetic:'/ˈtɾa.βaxo/',category:'diario',difficulty:1},
    {word:'comer',meaning:'吃',phonetic:'/ko.ˈmeɾ/',category:'diario',difficulty:1},
    {word:'beber',meaning:'喝',phonetic:'/be.ˈβeɾ/',category:'diario',difficulty:1},
    {word:'dormir',meaning:'睡觉',phonetic:'/doɾ.ˈmiɾ/',category:'diario',difficulty:1},
    {word:'hablar',meaning:'说话',phonetic:'/a.ˈblaɾ/',category:'diario',difficulty:1},
    {word:'leer',meaning:'阅读',phonetic:'/le.ˈeɾ/',category:'diario',difficulty:1},
    {word:'escribir',meaning:'写',phonetic:'/es.kɾi.ˈβiɾ/',category:'diario',difficulty:2},
    {word:'caminar',meaning:'走路',phonetic:'/ka.mi.ˈnaɾ/',category:'diario',difficulty:2},
    {word:'correr',meaning:'跑步',phonetic:'/ko.ˈɾeɾ/',category:'diario',difficulty:1},
    {word:'comprar',meaning:'买',phonetic:'/kom.ˈpɾaɾ/',category:'diario',difficulty:1},
    {word:'vender',meaning:'卖',phonetic:'/ben.ˈdeɾ/',category:'diario',difficulty:1},
    {word:'cocinar',meaning:'做饭',phonetic:'/ko.θi.ˈnaɾ/',category:'diario',difficulty:2},
    {word:'limpiar',meaning:'打扫',phonetic:'/lim.ˈpjaɾ/',category:'diario',difficulty:2},
    {word:'bañar',meaning:'洗澡',phonetic:'/ba.ˈɲaɾ/',category:'diario',difficulty:2},
    {word:'vestir',meaning:'穿衣',phonetic:'/bes.ˈtiɾ/',category:'diario',difficulty:2},
    {word:'despertar',meaning:'醒来',phonetic:'/des.peɾ.ˈtaɾ/',category:'diario',difficulty:2},
    {word:'levantarse',meaning:'起床',phonetic:'/le.βan.ˈtaɾ.se/',category:'diario',difficulty:3},
    {word:'acostarse',meaning:'就寝',phonetic:'/a.kos.ˈtaɾ.se/',category:'diario',difficulty:3},
    {word:'almorzar',meaning:'吃午饭',phonetic:'/al.moɾ.ˈθaɾ/',category:'diario',difficulty:2},
    {word:'merendar',meaning:'吃点心',phonetic:'/me.ɾen.ˈdaɾ/',category:'diario',difficulty:2},
    {word:'cepillar',meaning:'刷',phonetic:'/θe.pi.ˈʎaɾ/',category:'diario',difficulty:2},
    {word:'peinar',meaning:'梳头',phonetic:'/pei.ˈnaɾ/',category:'diario',difficulty:2},
    {word:'lavar',meaning:'洗',phonetic:'/la.ˈβaɾ/',category:'diario',difficulty:1},
    {word:'estudiar',meaning:'学习',phonetic:'/es.tu.ˈðjaɾ/',category:'diario',difficulty:2},
    {word:'practicar',meaning:'练习',phonetic:'/pɾak.ti.ˈkaɾ/',category:'diario',difficulty:2},
    {word:'necesitar',meaning:'需要',phonetic:'/ne.θe.si.ˈtaɾ/',category:'diario',difficulty:2},
    {word:'compartir',meaning:'分享',phonetic:'/kom.paɾ.ˈtiɾ/',category:'diario',difficulty:2},
    {word:'disfrutar',meaning:'享受',phonetic:'/dis.fɾu.ˈtaɾ/',category:'diario',difficulty:2},

    // ===== emociones (情感) =====
    {word:'feliz',meaning:'快乐的',phonetic:'/fe.ˈliθ/',category:'emociones',difficulty:1},
    {word:'triste',meaning:'悲伤的',phonetic:'/ˈtɾis.te/',category:'emociones',difficulty:1},
    {word:'enojado',meaning:'生气的',phonetic:'/e.no.ˈxa.ðo/',category:'emociones',difficulty:2},
    {word:'asustado',meaning:'害怕的',phonetic:'/a.sus.ˈta.ðo/',category:'emociones',difficulty:2},
    {word:'sorprendido',meaning:'惊讶的',phonetic:'/soɾ.pɾen.ˈdi.ðo/',category:'emociones',difficulty:3},
    {word:'emocionado',meaning:'兴奋的',phonetic:'/e.mo.θjo.ˈna.ðo/',category:'emociones',difficulty:3},
    {word:'aburrido',meaning:'无聊的',phonetic:'/a.bu.ˈɾi.ðo/',category:'emociones',difficulty:2},
    {word:'cansado',meaning:'疲倦的',phonetic:'/kan.ˈsa.ðo/',category:'emociones',difficulty:2},
    {word:'nervioso',meaning:'紧张的',phonetic:'/neɾ.ˈbjo.so/',category:'emociones',difficulty:2},
    {word:'contento',meaning:'满意的',phonetic:'/kon.ˈten.to/',category:'emociones',difficulty:2},
    {word:'preocupado',meaning:'担心的',phonetic:'/pɾe.o.ku.ˈpa.ðo/',category:'emociones',difficulty:3},
    {word:'agradecido',meaning:'感激的',phonetic:'/a.ɣɾa.ðe.ˈθi.ðo/',category:'emociones',difficulty:3},
    {word:'orgulloso',meaning:'骄傲的',phonetic:'/oɾ.ɣu.ˈʎo.so/',category:'emociones',difficulty:3},
    {word:'avergonzado',meaning:'尴尬的',phonetic:'/a.βeɾ.ɣon.ˈθa.ðo/',category:'emociones',difficulty:3},
    {word:'celoso',meaning:'嫉妒的',phonetic:'/θe.ˈlo.so/',category:'emociones',difficulty:2},
    {word:'confundido',meaning:'困惑的',phonetic:'/kom.fun.ˈdi.ðo/',category:'emociones',difficulty:3},
    {word:'tranquilo',meaning:'平静的',phonetic:'/tɾaŋ.ˈki.lo/',category:'emociones',difficulty:2},
    {word:'alegre',meaning:'愉快的',phonetic:'/a.ˈle.ɣɾe/',category:'emociones',difficulty:2},
    {word:'amor',meaning:'爱',phonetic:'/a.ˈmoɾ/',category:'emociones',difficulty:1},
    {word:'odio',meaning:'恨',phonetic:'/ˈo.ðjo/',category:'emociones',difficulty:1},
    {word:'esperanza',meaning:'希望',phonetic:'/es.pe.ˈɾan.θa/',category:'emociones',difficulty:2},
    {word:'miedo',meaning:'恐惧',phonetic:'/ˈmje.ðo/',category:'emociones',difficulty:1},
    {word:'ira',meaning:'愤怒',phonetic:'/ˈi.ɾa/',category:'emociones',difficulty:1},
    {word:'paz',meaning:'和平',phonetic:'/ˈpaθ/',category:'emociones',difficulty:1},
    {word:'alegría',meaning:'快乐',phonetic:'/a.le.ˈɣɾi.a/',category:'emociones',difficulty:2},
    {word:'tristeza',meaning:'悲伤',phonetic:'/tɾis.ˈte.θa/',category:'emociones',difficulty:2},
    {word:'soledad',meaning:'孤独',phonetic:'/so.le.ˈðað/',category:'emociones',difficulty:2},
    {word:'felicidad',meaning:'幸福',phonetic:'/fe.li.θi.ˈðað/',category:'emociones',difficulty:3},
    {word:'pasión',meaning:'热情',phonetic:'/pa.ˈsjon/',category:'emociones',difficulty:2},
    {word:'duda',meaning:'怀疑',phonetic:'/ˈdu.ða/',category:'emociones',difficulty:1},

    // ===== B2 Level (difficulty: 4) — 抽象词汇、学术术语、新闻媒体、职业用语 =====

    // --- B2: 抽象词汇 & 认知 (abstract & cognitive) ---
    {word:'concepto',meaning:'概念',phonetic:'/kon.ˈsep.to/',category:'emociones',difficulty:4},
    {word:'perspectiva',meaning:'视角',phonetic:'/peɾs.pek.ˈti.βa/',category:'emociones',difficulty:4},
    {word:'análisis',meaning:'分析',phonetic:'/a.ˈna.li.sis/',category:'emociones',difficulty:4},
    {word:'hipótesis',meaning:'假设',phonetic:'/i.ˈpo.te.sis/',category:'emociones',difficulty:4},
    {word:'conclusión',meaning:'结论',phonetic:'/koŋ.klu.ˈsjon/',category:'emociones',difficulty:4},
    {word:'argumento',meaning:'论点',phonetic:'/aɾ.ɣu.ˈmen.to/',category:'emociones',difficulty:4},
    {word:'evidencia',meaning:'证据',phonetic:'/e.bi.ˈðjen.θja/',category:'emociones',difficulty:4},
    {word:'interpretación',meaning:'解释',phonetic:'/in.teɾ.pɾe.ta.ˈθjon/',category:'emociones',difficulty:4},
    {word:'implicación',meaning:'含义',phonetic:'/im.pli.ka.ˈθjon/',category:'emociones',difficulty:4},
    {word:'deducción',meaning:'推论',phonetic:'/de.ðuk.ˈθjon/',category:'emociones',difficulty:4},
    {word:'juicio',meaning:'判断',phonetic:'/ˈxwi.θjo/',category:'emociones',difficulty:4},
    {word:'criterio',meaning:'标准',phonetic:'/kɾi.ˈte.rjo/',category:'emociones',difficulty:4},
    {word:'fundamento',meaning:'基础',phonetic:'/fun.da.ˈmen.to/',category:'emociones',difficulty:4},
    {word:'principio',meaning:'原则',phonetic:'/pɾin.ˈθi.pjo/',category:'emociones',difficulty:4},
    {word:'teoría',meaning:'理论',phonetic:'/te.ˈo.ɾja/',category:'emociones',difficulty:4},
    {word:'fenómeno',meaning:'现象',phonetic:'/fe.ˈno.me.no/',category:'emociones',difficulty:4},
    {word:'paradigma',meaning:'范式',phonetic:'/pa.ˈɾa.ðiɣ.ma/',category:'emociones',difficulty:4},
    {word:'enfoque',meaning:'方法/焦点',phonetic:'/em.ˈfo.ke/',category:'emociones',difficulty:4},
    {word:'perspectiva',meaning:'观点',phonetic:'/peɾs.pek.ˈti.βa/',category:'emociones',difficulty:4},
    {word:'controversia',meaning:'争议',phonetic:'/kon.tɾo.ˈbeɾ.sja/',category:'emociones',difficulty:4},
    {word:'ambigüedad',meaning:'歧义',phonetic:'/am.bi.ɣwe.ˈðað/',category:'emociones',difficulty:4},
    {word:'coherencia',meaning:'连贯性',phonetic:'/ko.e.ˈɾen.θja/',category:'emociones',difficulty:4},
    {word:'relevancia',meaning:'相关性',phonetic:'/re.le.ˈβan.θja/',category:'emociones',difficulty:4},
    {word:'veracidad',meaning:'真实性',phonetic:'/be.ra.ˈθi.ðað/',category:'emociones',difficulty:4},
    {word:'subjetivo',meaning:'主观的',phonetic:'/sub.xe.ˈti.βo/',category:'emociones',difficulty:4},

    // --- B2: 职业与商务 (professional & business) ---
    {word:'estrategia',meaning:'战略',phonetic:'/es.tɾa.ˈte.xja/',category:'viaje',difficulty:4},
    {word:'objetivo',meaning:'目标',phonetic:'/ob.xe.ˈti.βo/',category:'viaje',difficulty:4},
    {word:'meta',meaning:'目标/指标',phonetic:'/ˈme.ta/',category:'viaje',difficulty:4},
    {word:'presupuesto',meaning:'预算',phonetic:'/pɾe.su.ˈpwes.to/',category:'viaje',difficulty:4},
    {word:'inversión',meaning:'投资',phonetic:'/im.beɾ.ˈsjon/',category:'viaje',difficulty:4},
    {word:'beneficio',meaning:'利润/好处',phonetic:'/be.ne.ˈfi.θjo/',category:'viaje',difficulty:4},
    {word:'rentabilidad',meaning:'盈利能力',phonetic:'/ɾen.ta.bi.li.ˈðað/',category:'viaje',difficulty:4},
    {word:'mercancía',meaning:'商品',phonetic:'/meɾ.ˈkan.θja/',category:'viaje',difficulty:4},
    {word:'exportación',meaning:'出口',phonetic:'/eks.poɾ.ta.ˈθjon/',category:'viaje',difficulty:4},
    {word:'importación',meaning:'进口',phonetic:'/im.poɾ.ta.ˈθjon/',category:'viaje',difficulty:4},
    {word:'competencia',meaning:'竞争',phonetic:'/kom.pe.ˈten.θja/',category:'viaje',difficulty:4},
    {word:'negociación',meaning:'谈判',phonetic:'/ne.ɣo.θja.ˈθjon/',category:'viaje',difficulty:4},
    {word:'acuerdo',meaning:'协议',phonetic:'/a.ˈkweɾ.ðo/',category:'viaje',difficulty:4},
    {word:'contrato',meaning:'合同',phonetic:'/kon.ˈtɾa.to/',category:'viaje',difficulty:4},
    {word:'empresa',meaning:'企业',phonetic:'/em.ˈpɾe.sa/',category:'viaje',difficulty:4},
    {word:'gestión',meaning:'管理',phonetic:'/xes.ˈtjon/',category:'viaje',difficulty:4},
    {word:'recurso',meaning:'资源',phonetic:'/re.ˈkuɾ.so/',category:'viaje',difficulty:4},
    {word:'productividad',meaning:'生产力',phonetic:'/pɾo.ðuk.ti.bi.li.ˈðað/',category:'viaje',difficulty:4},
    {word:'candidato',meaning:'候选人',phonetic:'/kan.di.ˈða.to/',category:'viaje',difficulty:4},
    {word:'evaluación',meaning:'评估',phonetic:'/e.ba.lwa.ˈθjon/',category:'viaje',difficulty:4},
    {word:'promoción',meaning:'晋升/推广',phonetic:'/pɾo.mo.ˈθjon/',category:'viaje',difficulty:4},
    {word:'jornada',meaning:'工作日',phonetic:'/xoɾ.ˈna.ða/',category:'diario',difficulty:4},
    {word:'horario',meaning:'时间表',phonetic:'/o.ˈɾa.rjo/',category:'diario',difficulty:4},
    {word:'titular',meaning:'负责人/持有人',phonetic:'/ti.tu.ˈlaɾ/',category:'diario',difficulty:4},
    {word:'supervisor',meaning:'主管',phonetic:'/su.peɾ.ˈbi.soɾ/',category:'diario',difficulty:4},

    // --- B2: 新闻与媒体 (news & media) ---
    {word:'titular',meaning:'标题',phonetic:'/ti.tu.ˈlaɾ/',category:'diario',difficulty:4},
    {word:'editorial',meaning:'社论',phonetic:'/e.ði.to.ˈɾjal/',category:'diario',difficulty:4},
    {word:'artículo',meaning:'文章',phonetic:'/aɾ.ˈti.ku.lo/',category:'diario',difficulty:4},
    {word:'crónica',meaning:'新闻报导',phonetic:'/ˈkɾo.ni.ka/',category:'diario',difficulty:4},
    {word:'reportaje',meaning:'报道',phonetic:'/re.poɾ.ˈta.xe/',category:'diario',difficulty:4},
    {word:'corresponsal',meaning:'通讯记者',phonetic:'/ko.re.spon.ˈsal/',category:'diario',difficulty:4},
    {word:'cobertura',meaning:'新闻报道范围',phonetic:'/ko.beɾ.ˈtu.ɾa/',category:'diario',difficulty:4},
    {word:'encuesta',meaning:'民意调查',phonetic:'/en.ˈkwes.ta/',category:'diario',difficulty:4},
    {word:'sondeo',meaning:'调查',phonetic:'/son.ˈde.o/',category:'diario',difficulty:4},
    {word:'audiencia',meaning:'听众/收视率',phonetic:'/aw.ˈdjen.θja/',category:'diario',difficulty:4},
    {word:'emisión',meaning:'播出',phonetic:'/e.mi.ˈsjon/',category:'diario',difficulty:4},
    {word:'transmisión',meaning:'传输',phonetic:'/tɾanz.mi.ˈsjon/',category:'diario',difficulty:4},
    {word:'censura',meaning:'审查',phonetic:'/θen.ˈsu.ɾa/',category:'diario',difficulty:4},
    {word:'propaganda',meaning:'宣传',phonetic:'/pɾo.pa.ˈɣan.da/',category:'diario',difficulty:4},
    {word:'boletín',meaning:'简报',phonetic:'/bo.le.ˈtin/',category:'diario',difficulty:4},
    {word:'declaración',meaning:'声明',phonetic:'/de.kla.ra.ˈθjon/',category:'diario',difficulty:4},
    {word:'rueda de prensa',meaning:'记者会',phonetic:'/ˈrwe.ða ðe ˈpɾen.sa/',category:'diario',difficulty:4},
    {word:'actualidad',meaning:'时事',phonetic:'/ak.twa.li.ˈðað/',category:'diario',difficulty:4},
    {word:'suceso',meaning:'事件',phonetic:'/su.ˈθe.so/',category:'diario',difficulty:4},
    {word:'crisis',meaning:'危机',phonetic:'/ˈkɾi.sis/',category:'diario',difficulty:4},

    // --- B2: 社会与政治 (society & politics) ---
    {word:'ciudadanía',meaning:'公民身份',phonetic:'/θju.ða.ða.ˈni.a/',category:'viaje',difficulty:4},
    {word:'democracia',meaning:'民主',phonetic:'/de.mo.ˈkɾa.θja/',category:'viaje',difficulty:4},
    {word:'gobierno',meaning:'政府',phonetic:'/go.ˈbjeɾ.no/',category:'viaje',difficulty:4},
    {word:'política',meaning:'政治',phonetic:'/po.ˈli.ti.ka/',category:'viaje',difficulty:4},
    {word:'legislación',meaning:'立法',phonetic:'/le.xis.la.ˈθjon/',category:'viaje',difficulty:4},
    {word:'constitución',meaning:'宪法',phonetic:'/kon.sti.tu.ˈθjon/',category:'viaje',difficulty:4},
    {word:'derecho',meaning:'权利/法律',phonetic:'/de.ˈɾe.tʃo/',category:'viaje',difficulty:4},
    {word:'justicia',meaning:'正义',phonetic:'/xus.ˈti.θja/',category:'viaje',difficulty:4},
    {word:'igualdad',meaning:'平等',phonetic:'/i.ɣwal.ˈðað/',category:'viaje',difficulty:4},
    {word:'libertad',meaning:'自由',phonetic:'/li.βeɾ.ˈtað/',category:'viaje',difficulty:4},
    {word:'solidaridad',meaning:'团结',phonetic:'/so.li.ða.ɾi.ˈðað/',category:'viaje',difficulty:4},
    {word:'tolerancia',meaning:'宽容',phonetic:'/to.le.ˈɾan.θja/',category:'viaje',difficulty:4},
    {word:'discriminación',meaning:'歧视',phonetic:'/dis.kɾi.mi.na.ˈθjon/',category:'viaje',difficulty:4},
    {word:'manifestación',meaning:'示威',phonetic:'/ma.ni.fes.ta.ˈθjon/',category:'viaje',difficulty:4},
    {word:'referéndum',meaning:'公投',phonetic:'/re.fe.ˈɾen.dum/',category:'viaje',difficulty:4},
    {word:'debate',meaning:'辩论',phonetic:'/de.ˈba.te/',category:'viaje',difficulty:4},
    {word:'votación',meaning:'投票',phonetic:'/bo.ta.ˈθjon/',category:'viaje',difficulty:4},
    {word:'minoría',meaning:'少数',phonetic:'/mi.no.ˈɾi.a/',category:'viaje',difficulty:4},
    {word:'mayoría',meaning:'多数',phonetic:'/ma.jo.ˈɾi.a/',category:'viaje',difficulty:4},
    {word:'oposición',meaning:'反对',phonetic:'/o.po.si.ˈθjon/',category:'viaje',difficulty:4},

    // --- B2: 教育与学术 (education & academic) ---
    {word:'currículum',meaning:'课程/简历',phonetic:'/ku.ˈri.ku.lum/',category:'numeros',difficulty:4},
    {word:'diplomado',meaning:'文凭课程',phonetic:'/di.plo.ˈma.ðo/',category:'numeros',difficulty:4},
    {word:'posgrado',meaning:'研究生',phonetic:'/pos.ˈɣɾa.ðo/',category:'numeros',difficulty:4},
    {word:'investigación',meaning:'研究',phonetic:'/im.bes.ti.ɣa.ˈθjon/',category:'numeros',difficulty:4},
    {word:'tesis',meaning:'论文',phonetic:'/ˈte.sis/',category:'numeros',difficulty:4},
    {word:'bibliografía',meaning:'参考文献',phonetic:'/bi.blio.ɣɾa.ˈfi.a/',category:'numeros',difficulty:4},
    {word:'metodología',meaning:'方法论',phonetic:'/me.to.ðo.lo.ˈxi.a/',category:'numeros',difficulty:4},
    {word:'asignatura',meaning:'科目',phonetic:'/a.sig.na.ˈtu.ɾa/',category:'numeros',difficulty:4},
    {word:'calificación',meaning:'成绩',phonetic:'/ka.li.fi.ka.ˈθjon/',category:'numeros',difficulty:4},
    {word:'evaluación',meaning:'评估',phonetic:'/e.ba.lwa.ˈθjon/',category:'numeros',difficulty:4},
    {word:'conocimiento',meaning:'知识',phonetic:'/ko.no.θi.ˈmjen.to/',category:'numeros',difficulty:4},
    {word:'habilidad',meaning:'技能',phonetic:'/a.bi.li.ˈðað/',category:'numeros',difficulty:4},
    {word:'competencia',meaning:'能力',phonetic:'/kom.pe.ˈten.θja/',category:'numeros',difficulty:4},
    {word:'aprendizaje',meaning:'学习',phonetic:'/a.pɾen.di.ˈsa.xe/',category:'numeros',difficulty:4},
    {word:'enseñanza',meaning:'教学',phonetic:'/en.se.ˈɲan.θa/',category:'numeros',difficulty:4},
    {word:'formación',meaning:'培训',phonetic:'/foɾ.ma.ˈθjon/',category:'numeros',difficulty:4},
    {word:'especialización',meaning:'专业方向',phonetic:'/es.pe.θja.li.θa.ˈθjon/',category:'numeros',difficulty:4},
    {word:'seminario',meaning:'研讨会',phonetic:'/se.mi.ˈna.rjo/',category:'numeros',difficulty:4},
    {word:'conferencia',meaning:'讲座',phonetic:'/kom.fe.ˈɾen.θja/',category:'numeros',difficulty:4},
    {word:'práctica',meaning:'实践',phonetic:'/ˈpɾak.ti.ka/',category:'numeros',difficulty:4},

    // --- B2: 科技与环境 (technology & environment) ---
    {word:'tecnología',meaning:'技术',phonetic:'/tek.no.ˈlo.xja/',category:'clima',difficulty:4},
    {word:'innovación',meaning:'创新',phonetic:'/in.no.ba.ˈθjon/',category:'clima',difficulty:4},
    {word:'algoritmo',meaning:'算法',phonetic:'/al.ɣo.ˈɾiθ.mo/',category:'clima',difficulty:4},
    {word:'software',meaning:'软件',phonetic:'/ˈsoft.waɾ/',category:'clima',difficulty:4},
    {word:'hardware',meaning:'硬件',phonetic:'/ˈaɾd.waɾ/',category:'clima',difficulty:4},
    {word:'base de datos',meaning:'数据库',phonetic:'/ˈba.se ðe ˈda.tos/',category:'clima',difficulty:4},
    {word:'inteligencia artificial',meaning:'人工智能',phonetic:'/in.te.li.ˈxen.θja aɾ.ti.fi.ˈθjal/',category:'clima',difficulty:4},
    {word:'medio ambiente',meaning:'环境',phonetic:'/ˈme.ðjo am.bjen.te/',category:'clima',difficulty:4},
    {word:'contaminación',meaning:'污染',phonetic:'/kon.ta.mi.na.ˈθjon/',category:'clima',difficulty:4},
    {word:'emisión',meaning:'排放',phonetic:'/e.mi.ˈsjon/',category:'clima',difficulty:4},
    {word:'sostenibilidad',meaning:'可持续性',phonetic:'/sos.te.ni.bi.li.ˈðað/',category:'clima',difficulty:4},
    {word:'reciclaje',meaning:'回收',phonetic:'/re.θi.ˈkla.xe/',category:'clima',difficulty:4},
    {word:'ecosistema',meaning:'生态系统',phonetic:'/e.ko.sis.ˈte.ma/',category:'clima',difficulty:4},
    {word:'biodiversidad',meaning:'生物多样性',phonetic:'/bi.o.di.beɾ.si.ˈðað/',category:'clima',difficulty:4},
    {word:'renovable',meaning:'可再生的',phonetic:'/re.no.ˈβa.ble/',category:'clima',difficulty:4},
    {word:'energía',meaning:'能源',phonetic:'/e.neɾ.ˈxi.a/',category:'clima',difficulty:4},
    {word:'cambio climático',meaning:'气候变化',phonetic:'/ˈkam.bjo kli.ˈma.ti.ko/',category:'clima',difficulty:4},
    {word:'sequía',meaning:'干旱',phonetic:'/se.ˈki.a/',category:'clima',difficulty:4},
    {word:'deforestación',meaning:'砍伐森林',phonetic:'/de.foɾ.es.ta.ˈθjon/',category:'clima',difficulty:4},
    {word:'conservación',meaning:'保护',phonetic:'/kon.seɾ.ba.ˈθjon/',category:'clima',difficulty:4},

    // --- B2: 健康与医学 (health & medicine) ---
    {word:'síntoma',meaning:'症状',phonetic:'/ˈsim.to.ma/',category:'cuerpo',difficulty:4},
    {word:'diagnóstico',meaning:'诊断',phonetic:'/djaɣ.ˈnos.ti.ko/',category:'cuerpo',difficulty:4},
    {word:'tratamiento',meaning:'治疗',phonetic:'/tɾa.ta.ˈmjen.to/',category:'cuerpo',difficulty:4},
    {word:'cirugía',meaning:'手术',phonetic:'/θi.ɾu.ˈxi.a/',category:'cuerpo',difficulty:4},
    {word:'medicamento',meaning:'药物',phonetic:'/me.ði.ka.ˈmen.to/',category:'cuerpo',difficulty:4},
    {word:'prescripción',meaning:'处方',phonetic:'/pɾes.kɾip.ˈθjon/',category:'cuerpo',difficulty:4},
    {word:'vacuna',meaning:'疫苗',phonetic:'/ba.ˈku.na/',category:'cuerpo',difficulty:4},
    {word:'epidemia',meaning:'流行病',phonetic:'/e.pi.ˈde.mja/',category:'cuerpo',difficulty:4},
    {word:'pandemia',meaning:'大流行',phonetic:'/pan.ˈde.mja/',category:'cuerpo',difficulty:4},
    {word:'prevención',meaning:'预防',phonetic:'/pɾe.βen.ˈθjon/',category:'cuerpo',difficulty:4},
    {word:'rehabilitación',meaning:'康复',phonetic:'/re.a.bi.li.ta.ˈθjon/',category:'cuerpo',difficulty:4},
    {word:'nutrición',meaning:'营养',phonetic:'/nu.tɾi.ˈθjon/',category:'cuerpo',difficulty:4},
    {word:'infección',meaning:'感染',phonetic:'/in.fek.ˈθjon/',category:'cuerpo',difficulty:4},
    {word:'alergia',meaning:'过敏',phonetic:'/a.ˈleɾ.xja/',category:'cuerpo',difficulty:4},
    {word:'crónico',meaning:'慢性的',phonetic:'/ˈkɾo.ni.ko/',category:'cuerpo',difficulty:4},
    {word:'bienestar',meaning:'健康/幸福',phonetic:'/bje.nes.ˈtaɾ/',category:'cuerpo',difficulty:4},
    {word:'salud pública',meaning:'公共卫生',phonetic:'/sa.ˈluð ˈpu.βli.ka/',category:'cuerpo',difficulty:4},
    {word:'hospitalización',meaning:'住院',phonetic:'/os.pi.ta.li.θa.ˈθjon/',category:'cuerpo',difficulty:4},
    {word:'emergencia',meaning:'急诊',phonetic:'/e.meɾ.ˈxen.θja/',category:'cuerpo',difficulty:4},
    {word:'terapia',meaning:'治疗/疗法',phonetic:'/te.ˈɾa.pja/',category:'cuerpo',difficulty:4},

    // --- B2: 情感与抽象描述 (emotions & abstract descriptions) ---
    {word:'frustración',meaning:'挫折',phonetic:'/fɾus.tɾa.ˈθjon/',category:'emociones',difficulty:4},
    {word:'resiliencia',meaning:'韧性',phonetic:'/re.si.ˈljen.θja/',category:'emociones',difficulty:4},
    {word:'empatía',meaning:'共情',phonetic:'/em.pa.ˈti.a/',category:'emociones',difficulty:4},
    {word:'nostalgia',meaning:'怀旧',phonetic:'/nos.ˈtal.xja/',category:'emociones',difficulty:4},
    {word:'melancolía',meaning:'忧郁',phonetic:'/me.laŋ.ko.ˈli.a/',category:'emociones',difficulty:4},
    {word:'indiferencia',meaning:'冷漠',phonetic:'/in.di.fe.ˈɾen.θja/',category:'emociones',difficulty:4},
    {word:'compasión',meaning:'同情',phonetic:'/kom.pa.ˈsjon/',category:'emociones',difficulty:4},
    {word:'benevolencia',meaning:'仁慈',phonetic:'/be.ne.bo.ˈlen.θja/',category:'emociones',difficulty:4},
    {word:'hostilidad',meaning:'敌意',phonetic:'/os.ti.li.ˈðað/',category:'emociones',difficulty:4},
    {word:'tentación',meaning:'诱惑',phonetic:'/ten.ta.ˈθjon/',category:'emociones',difficulty:4},
    {word:'satisfacción',meaning:'满意',phonetic:'/sa.tis.fak.ˈθjon/',category:'emociones',difficulty:4},
    {word:'motivación',meaning:'动机',phonetic:'/mo.ti.ba.ˈθjon/',category:'emociones',difficulty:4},
    {word:'inspiración',meaning:'灵感',phonetic:'/ins.pi.ra.ˈθjon/',category:'emociones',difficulty:4},
    {word:'admiración',meaning:'钦佩',phonetic:'/að.mi.ra.ˈθjon/',category:'emociones',difficulty:4},
    {word:'desilusión',meaning:'失望',phonetic:'/de.si.lu.ˈsjon/',category:'emociones',difficulty:4},
    {word:'permiso',meaning:'允许',phonetic:'/peɾ.ˈmi.so/',category:'emociones',difficulty:4},
    {word:'obligación',meaning:'义务',phonetic:'/o.bli.ɣa.ˈθjon/',category:'emociones',difficulty:4},
    {word:'responsabilidad',meaning:'责任',phonetic:'/res.pon.sa.bi.li.ˈðað/',category:'emociones',difficulty:4},
    {word:'conciencia',meaning:'意识',phonetic:'/kon.ˈθjen.θja/',category:'emociones',difficulty:4},
    {word:'intuición',meaning:'直觉',phonetic:'/in.tui.ˈθjon/',category:'emociones',difficulty:4},

    // --- B2: 日常生活进阶 (advanced daily life) ---
    {word:'recibo',meaning:'收据',phonetic:'/re.ˈθi.βo/',category:'comida',difficulty:4},
    {word:'factura',meaning:'发票',phonetic:'/fak.ˈtu.ɾa/',category:'comida',difficulty:4},
    {word:'garantía',meaning:'保证/保修',phonetic:'/ga.ɾan.ˈti.a/',category:'comida',difficulty:4},
    {word:'reclamación',meaning:'投诉',phonetic:'/re.kla.ma.ˈθjon/',category:'comida',difficulty:4},
    {word:'devolución',meaning:'退货',phonetic:'/de.βo.lu.ˈθjon/',category:'comida',difficulty:4},
    {word:'descuento',meaning:'折扣',phonetic:'/des.ˈkwento/',category:'comida',difficulty:4},
    {word:'oferta',meaning:'特价',phonetic:'/o.ˈfeɾ.ta/',category:'comida',difficulty:4},
    {word:'instalación',meaning:'安装',phonetic:'/ins.ta.la.ˈθjon/',category:'comida',difficulty:4},
    {word:'mantenimiento',meaning:'维护',phonetic:'/man.te.ni.ˈmjen.to/',category:'comida',difficulty:4},
    {word:'suscripción',meaning:'订阅',phonetic:'/sus.kɾip.ˈθjon/',category:'comida',difficulty:4},
    {word:'vecindario',meaning:'社区',phonetic:'/be.θin.ˈda.rjo/',category:'comida',difficulty:4},
    {word:'urbanización',meaning:'城市化',phonetic:'/uɾ.ba.ni.θa.ˈθjon/',category:'comida',difficulty:4},
    {word:'transporte público',meaning:'公共交通',phonetic:'/tɾans.ˈpoɾ.te ˈpu.βli.ko/',category:'comida',difficulty:4},
    {word:'infraestructura',meaning:'基础设施',phonetic:'/in.fɾa.es.tɾuk.ˈtu.ɾa/',category:'comida',difficulty:4},
    {word:'servicio',meaning:'服务',phonetic:'/seɾ.ˈbi.θjo/',category:'comida',difficulty:4},

    // ===== C1 Level (difficulty: 5) — 文学表达、高级习语、正式术语 =====

    // --- C1: 文学与高雅词汇 (literary & refined vocabulary) ---
    {word:'albor',meaning:'黎明',phonetic:'/ˈal.βoɾ/',category:'clima',difficulty:5},
    {word:'ocaso',meaning:'日落/衰落',phonetic:'/o.ˈka.so/',category:'clima',difficulty:5},
    {word:'aurora',meaning:'曙光',phonetic:'/aw.ˈɾo.ɾa/',category:'clima',difficulty:5},
    {word:'crepúsculo',meaning:'黄昏',phonetic:'/kɾe.ˈpus.ku.lo/',category:'clima',difficulty:5},
    {word:'penumbra',meaning:'半暗',phonetic:'/pe.ˈnum.bɾa/',category:'clima',difficulty:5},
    {word:'efímero',meaning:'短暂的',phonetic:'/e.ˈfi.me.ɾo/',category:'clima',difficulty:5},
    {word:'perpetuo',meaning:'永恒的',phonetic:'/peɾ.ˈpe.tuo/',category:'clima',difficulty:5},
    {word:'incesante',meaning:'不停的',phonetic:'/in.θe.ˈsan.te/',category:'clima',difficulty:5},
    {word:'luminiscencia',meaning:'发光',phonetic:'/lu.mi.nis.ˈθen.θja/',category:'clima',difficulty:5},
    {word:'bruma',meaning:'薄雾',phonetic:'/ˈbɾu.ma/',category:'clima',difficulty:5},
    {word:'vapor',meaning:'蒸汽',phonetic:'/ba.ˈpoɾ/',category:'clima',difficulty:5},
    {word:'resplandor',meaning:'光辉',phonetic:'/res.plan.ˈðoɾ/',category:'clima',difficulty:5},
    {word:'fulgor',meaning:'闪耀',phonetic:'/ful.ˈɣoɾ/',category:'clima',difficulty:5},
    {word:'ceniza',meaning:'灰烬',phonetic:'/θe.ˈni.θa/',category:'clima',difficulty:5},
    {word:'destello',meaning:'闪光',phonetic:'/des.ˈte.ʎo/',category:'clima',difficulty:5},

    // --- C1: 高级情感与心理 (advanced emotions & psychology) ---
    {word:'desdén',meaning:'蔑视',phonetic:'/dez.ˈðen/',category:'emociones',difficulty:5},
    {word:'angustia',meaning:'极度痛苦',phonetic:'/aŋ.ˈɡwis.tja/',category:'emociones',difficulty:5},
    {word:'angustia',meaning:'焦虑/痛苦',phonetic:'/aŋ.ˈɡus.tja/',category:'emociones',difficulty:5},
    {word:'desvelo',meaning:'焦虑/失眠',phonetic:'/dez.ˈbe.lo/',category:'emociones',difficulty:5},
    {word:'ensimismamiento',meaning:'自我沉醉',phonetic:'/en.si.miz.ma.ˈmjen.to/',category:'emociones',difficulty:5},
    {word:'anhelo',meaning:'渴望',phonetic:'/a.ˈne.lo/',category:'emociones',difficulty:5},
    {word:'desazón',meaning:'不安',phonetic:'/de.sa.ˈθon/',category:'emociones',difficulty:5},
    {word:'hartazgo',meaning:'厌烦',phonetic:'/aɾ.ˈtaθ.ɣo/',category:'emociones',difficulty:5},
    {word:'desconsuelo',meaning:'极度悲伤',phonetic:'/des.kon.ˈswe.lo/',category:'emociones',difficulty:5},
    {word:'aflicción',meaning:'痛苦',phonetic:'/a.flik.ˈθjon/',category:'emociones',difficulty:5},
    {word:'congoja',meaning:'悲痛',phonetic:'/koŋ.ˈgo.xa/',category:'emociones',difficulty:5},
    {word:'pesadumbre',meaning:'忧伤',phonetic:'/pe.sa.ˈðum.bɾe/',category:'emociones',difficulty:5},
    {word:'tribulación',meaning:'磨难',phonetic:'/tɾi.bu.la.ˈθjon/',category:'emociones',difficulty:5},
    {word:'regocijo',meaning:'欢乐',phonetic:'/re.ɣo.ˈθi.xo/',category:'emociones',difficulty:5},
    {word:'júbilo',meaning:'欢腾',phonetic:'/ˈxu.bi.lo/',category:'emociones',difficulty:5},
    {word:'arrobamiento',meaning:'入迷',phonetic:'/a.ro.ba.ˈmjen.to/',category:'emociones',difficulty:5},
    {word:'estupor',meaning:'茫然',phonetic:'/es.tu.ˈpoɾ/',category:'emociones',difficulty:5},
    {word:'perplejidad',meaning:'困惑',phonetic:'/peɾ.ple.xi.ˈðað/',category:'emociones',difficulty:5},
    {word:'atolondramiento',meaning:'慌乱',phonetic:'/a.to.lon.dɾa.ˈmjen.to/',category:'emociones',difficulty:5},
    {word:'desconcierto',meaning:'慌张',phonetic:'/des.kon.ˈθjeɾ.to/',category:'emociones',difficulty:5},

    // --- C1: 哲学与思想 (philosophy & thought) ---
    {word:'existencia',meaning:'存在',phonetic:'/ek.sis.ˈten.θja/',category:'emociones',difficulty:5},
    {word:'esencia',meaning:'本质',phonetic:'/e.ˈsen.θja/',category:'emociones',difficulty:5},
    {word:'ontología',meaning:'本体论',phonetic:'/on.to.lo.ˈxi.a/',category:'emociones',difficulty:5},
    {word:'epistemología',meaning:'认识论',phonetic:'/e.pis.te.mo.lo.ˈxi.a/',category:'emociones',difficulty:5},
    {word:'dialéctica',meaning:'辩证法',phonetic:'/dja.ˈlek.ti.ka/',category:'emociones',difficulty:5},
    {word:'trascendencia',meaning:'超越性',phonetic:'/tɾas.θen.ˈðen.θja/',category:'emociones',difficulty:5},
    {word:'inmanencia',meaning:'内在性',phonetic:'/in.ma.ˈnen.θja/',category:'emociones',difficulty:5},
    {word:'ética',meaning:'伦理学',phonetic:'/ˈe.ti.ka/',category:'emociones',difficulty:5},
    {word:'moralidad',meaning:'道德',phonetic:'/mo.ra.li.ˈðað/',category:'emociones',difficulty:5},
    {word:'conocimiento',meaning:'认知',phonetic:'/ko.no.θi.ˈmjen.to/',category:'emociones',difficulty:5},
    {word:'sabiduría',meaning:'智慧',phonetic:'/sa.bi.ðu.ˈɾi.a/',category:'emociones',difficulty:5},
    {word:'verdad',meaning:'真理',phonetic:'/beɾ.ˈðað/',category:'emociones',difficulty:5},
    {word:'razón',meaning:'理性',phonetic:'/rra.ˈθon/',category:'emociones',difficulty:5},
    {word:'conciencia',meaning:'良心',phonetic:'/kon.ˈθjen.θja/',category:'emociones',difficulty:5},
    {word:'contingencia',meaning:'偶然性',phonetic:'/kon.tin.xen.ˈθja/',category:'emociones',difficulty:5},
    {word:'necesidad',meaning:'必然性',phonetic:'/ne.θe.si.ˈðað/',category:'emociones',difficulty:5},
    {word:'absoluto',meaning:'绝对的',phonetic:'/ab.so.ˈlu.to/',category:'emociones',difficulty:5},
    {word:'relativismo',meaning:'相对主义',phonetic:'/re.la.ti.ˈβis.mo/',category:'emociones',difficulty:5},
    {word:'escepticismo',meaning:'怀疑论',phonetic:'/es.θep.ti.ˈθis.mo/',category:'emociones',difficulty:5},
    {word:'dogmatismo',meaning:'教条主义',phonetic:'/doɣ.ma.ˈtis.mo/',category:'emociones',difficulty:5},

    // --- C1: 高级动词与表达 (advanced verbs & expressions) ---
    {word:'desentrañar',meaning:'揭示/解开',phonetic:'/de.sen.tɾa.ˈɲaɾ/',category:'diario',difficulty:5},
    {word:'entretejer',meaning:'交织',phonetic:'/en.tɾe.te.ˈxeɾ/',category:'diario',difficulty:5},
    {word:'converger',meaning:'汇聚',phonetic:'/kom.beɾ.ˈxeɾ/',category:'diario',difficulty:5},
    {word:'divergir',meaning:'分歧',phonetic:'/di.βeɾ.ˈxiɾ/',category:'diario',difficulty:5},
    {word:'potenciar',meaning:'增强',phonetic:'/po.ten.ˈθjaɾ/',category:'diario',difficulty:5},
    {word:'menoscabar',meaning:'损害',phonetic:'/me.nos.ka.ˈbaɾ/',category:'diario',difficulty:5},
    {word:'coartar',meaning:'限制',phonetic:'/ko.aɾ.ˈtaɾ/',category:'diario',difficulty:5},
    {word:'deslindar',meaning:'划定界限',phonetic:'/dez.lin.ˈdaɾ/',category:'diario',difficulty:5},
    {word:'vislumbrar',meaning:'隐约看见',phonetic:'/biz.lum.ˈbɾaɾ/',category:'diario',difficulty:5},
    {word:'atelarañar',meaning:'使着迷',phonetic:'/a.te.la.ɾa.ˈɲaɾ/',category:'diario',difficulty:5},
    {word:'ensanchar',meaning:'扩展',phonetic:'/en.san.ˈtʃaɾ/',category:'diario',difficulty:5},
    {word:'acuciar',meaning:'催促',phonetic:'/a.ˈku.θjaɾ/',category:'diario',difficulty:5},
    {word:'desbordar',meaning:'溢出',phonetic:'/dez.βoɾ.ˈðaɾ/',category:'diario',difficulty:5},
    {word:'reivindicar',meaning:'要求恢复',phonetic:'/rejm.biŋ.di.ˈkaɾ/',category:'diario',difficulty:5},
    {word:'plasmarse',meaning:'体现',phonetic:'/ˈplaz.maɾ.se/',category:'diario',difficulty:5},
    {word:'catalizar',meaning:'催化',phonetic:'/ka.ta.li.ˈθaɾ/',category:'diario',difficulty:5},
    {word:'congregar',meaning:'聚集',phonetic:'/koŋ.ɡɾe.ˈɣaɾ/',category:'diario',difficulty:5},
    {word:'proscenio',meaning:'前台',phonetic:'/pɾos.ˈθe.njo/',category:'diario',difficulty:5},
    {word:'empoderar',meaning:'赋权',phonetic:'/em.po.de.ˈɾaɾ/',category:'diario',difficulty:5},
    {word:'entrelazar',meaning:'交织/联系',phonetic:'/en.tɾe.la.ˈθaɾ/',category:'diario',difficulty:5},

    // --- C1: 正式与法律术语 (formal & legal terms) ---
    {word:'disposición',meaning:'规定',phonetic:'/dis.po.si.ˈθjon/',category:'viaje',difficulty:5},
    {word:'mandamiento',meaning:'命令/戒律',phonetic:'/man.da.ˈmjen.to/',category:'viaje',difficulty:5},
    {word:'jurisdicción',meaning:'管辖权',phonetic:'/xu.ris.ðik.ˈθjon/',category:'viaje',difficulty:5},
    {word:'tribunal',meaning:'法庭',phonetic:'/tɾi.bu.ˈnal/',category:'viaje',difficulty:5},
    {word:'magistrado',meaning:'法官',phonetic:'/ma.xis.ˈtɾa.ðo/',category:'viaje',difficulty:5},
    {word:'testimonio',meaning:'证词',phonetic:'/tes.ti.ˈmo.njo/',category:'viaje',difficulty:5},
    {word:'veredicto',meaning:'判决',phonetic:'/be.ɾe.ˈðik.to/',category:'viaje',difficulty:5},
    {word:'apelación',meaning:'上诉',phonetic:'/a.pe.la.ˈθjon/',category:'viaje',difficulty:5},
    {word:'indemnización',meaning:'赔偿',phonetic:'/in.de.mni.θa.ˈθjon/',category:'viaje',difficulty:5},
    {word:'infracción',meaning:'违规',phonetic:'/in.fɾak.ˈθjon/',category:'viaje',difficulty:5},
    {word:'delito',meaning:'罪行',phonetic:'/de.ˈli.to/',category:'viaje',difficulty:5},
    {word:'pena',meaning:'刑罚',phonetic:'/ˈpe.na/',category:'viaje',difficulty:5},
    {word:'absolución',meaning:'宣判无罪',phonetic:'/ab.so.lu.ˈθjon/',category:'viaje',difficulty:5},
    {word:'condena',meaning:'定罪',phonetic:'/kon.ˈde.na/',category:'viaje',difficulty:5},
    {word:'litigio',meaning:'诉讼',phonetic:'/li.ˈti.xjo/',category:'viaje',difficulty:5},
    {word:'arbitraje',meaning:'仲裁',phonetic:'/aɾ.bi.ˈtɾa.xe/',category:'viaje',difficulty:5},
    {word:'notario',meaning:'公证员',phonetic:'/no.ˈta.rjo/',category:'viaje',difficulty:5},
    {word:'testamento',meaning:'遗嘱',phonetic:'/tes.ta.ˈmen.to/',category:'viaje',difficulty:5},
    {word:'herencia',meaning:'遗产',phonetic:'/e.ˈɾen.θja/',category:'viaje',difficulty:5},
    {word:'custodia',meaning:'监护权',phonetic:'/kus.ˈto.ðja/',category:'viaje',difficulty:5},

    // --- C1: 文学修辞与描写 (literary rhetoric & description) ---
    {word:'alegoría',meaning:'寓言',phonetic:'/a.le.ɣo.ˈɾi.a/',category:'numeros',difficulty:5},
    {word:'metáfora',meaning:'隐喻',phonetic:'/me.ˈta.fo.ɾa/',category:'numeros',difficulty:5},
    {word:'símil',meaning:'明喻',phonetic:'/ˈsi.mil/',category:'numeros',difficulty:5},
    {word:'hipérbole',meaning:'夸张',phonetic:'/i.ˈpeɾ.bo.le/',category:'numeros',difficulty:5},
    {word:'ironía',meaning:'讽刺',phonetic:'/i.ɾo.ˈni.a/',category:'numeros',difficulty:5},
    {word:'paradoja',meaning:'悖论',phonetic:'/pa.ˈɾa.ðo.xa/',category:'numeros',difficulty:5},
    {word:'oxímoron',meaning:'矛盾修辞',phonetic:'/ok.si.ˈmo.ɾon/',category:'numeros',difficulty:5},
    {word:'sinécdoque',meaning:'提喻',phonetic:'/si.ˈnek.do.ke/',category:'numeros',difficulty:5},
    {word:'metonimia',meaning:'换喻',phonetic:'/me.to.ˈni.mja/',category:'numeros',difficulty:5},
    {word:'prosopopeya',meaning:'拟人',phonetic:'/pɾo.so.po.pe.ˈa/',category:'numeros',difficulty:5},
    {word:'elegía',meaning:'挽歌',phonetic:'/e.ˈle.xja/',category:'numeros',difficulty:5},
    {word:'oda',meaning:'颂歌',phonetic:'/ˈo.ða/',category:'numeros',difficulty:5},
    {word:'soneto',meaning:'十四行诗',phonetic:'/so.ˈne.to/',category:'numeros',difficulty:5},
    {word:'epílogo',meaning:'尾声',phonetic:'/e.ˈpi.lo.ɣo/',category:'numeros',difficulty:5},
    {word:'prólogo',meaning:'序言',phonetic:'/ˈpro.lo.ɣo/',category:'numeros',difficulty:5},
    {word:'narrativa',meaning:'叙事',phonetic:'/na.ˈɾa.ti.βa/',category:'numeros',difficulty:5},
    {word:'poesía',meaning:'诗歌',phonetic:'/po.e.ˈsi.a/',category:'numeros',difficulty:5},
    {word:'ensayo',meaning:'散文/论文',phonetic:'/en.ˈsa.ʎo/',category:'numeros',difficulty:5},
    {word:'crítica',meaning:'评论',phonetic:'/ˈkɾi.ti.ka/',category:'numeros',difficulty:5},
    {word:'hermenéutica',meaning:'诠释学',phonetic:'/eɾ.me.ˈneu.ti.ka/',category:'numeros',difficulty:5},

    // --- C1: 高级形容词 (advanced adjectives) ---
    {word:'insospechado',meaning:'意想不到的',phonetic:'/in.so.spe.ˈtʃa.ðo/',category:'colores',difficulty:5},
    {word:'inquebrantable',meaning:'不可破的',phonetic:'/im.ke.bɾan.ˈta.ble/',category:'colores',difficulty:5},
    {word:'inescrutable',meaning:'不可理解的',phonetic:'/i.nes.kɾu.ˈta.ble/',category:'colores',difficulty:5},
    {word:'innegable',meaning:'不可否认的',phonetic:'/i.ne.ˈɣa.ble/',category:'colores',difficulty:5},
    {word:'inexorable',meaning:'不可阻挡的',phonetic:'/i.nek.so.ˈɾa.ble/',category:'colores',difficulty:5},
    {word:'imponente',meaning:'壮观的',phonetic:'/im.po.ˈnen.te/',category:'colores',difficulty:5},
    {word:'majestuoso',meaning:'庄严的',phonetic:'/ma.xes.tu.ˈo.so/',category:'colores',difficulty:5},
    {word:'vacilante',meaning:'犹豫的',phonetic:'/ba.θi.ˈlan.te/',category:'colores',difficulty:5},
    {word:'impertérrito',meaning:'镇定的',phonetic:'/im.peɾ.ˈte.ri.to/',category:'colores',difficulty:5},
    {word:'recóndito',meaning:'偏僻的',phonetic:'/re.ˈkon.di.to/',category:'colores',difficulty:5},
    {word:'lúgubre',meaning:'阴沉的',phonetic:'/ˈlu.ɣu.bɾe/',category:'colores',difficulty:5},
    {word:'sombrio',meaning:'阴暗的',phonetic:'/ˈsom.bɾjo/',category:'colores',difficulty:5},
    {word:'sereno',meaning:'宁静的',phonetic:'/se.ˈɾe.no/',category:'colores',difficulty:5},
    {word:'plácido',meaning:'平静的',phonetic:'/ˈpla.θi.ðo/',category:'colores',difficulty:5},
    {word:'tupido',meaning:'浓密的',phonetic:'/tu.ˈpi.ðo/',category:'colores',difficulty:5},
    {word:'lenifique',meaning:'柔和的',phonetic:'/le.ni.fi.ke/',category:'colores',difficulty:5},
    {word:'férreo',meaning:'铁的/坚定的',phonetic:'/ˈfe.re.o/',category:'colores',difficulty:5},
    {word:'ídneo',meaning:'适合的',phonetic:'/ˈið.ne.o/',category:'colores',difficulty:5},
    {word:'letargo',meaning:'昏睡',phonetic:'/le.ˈtaɾ.ɣo/',category:'colores',difficulty:5},
    {word:'prístino',meaning:'原始的',phonetic:'/ˈpɾis.ti.no/',category:'colores',difficulty:5},

    // --- C1: 高级名词 — 文化与社会 (advanced nouns: culture & society) ---
    {word:'legado',meaning:'遗产/遗留',phonetic:'/le.ˈɣa.ðo/',category:'familia',difficulty:5},
    {word:'patrimonio',meaning:'文化遗产',phonetic:'/pa.tɾi.mo.ˈnjo/',category:'familia',difficulty:5},
    {word:'idiosincrasia',meaning:'特质',phonetic:'/i.ðjo.sin.ˈkɾa.sja/',category:'familia',difficulty:5},
    {word:'cosmovisión',meaning:'世界观',phonetic:'/koz.mo.bi.ˈsjon/',category:'familia',difficulty:5},
    {word:'mentalidad',meaning:'心态',phonetic:'/men.ta.li.ˈðað/',category:'familia',difficulty:5},
    {word:'estigma',meaning:'耻辱印记',phonetic:'/es.ˈtiɣ.ma/',category:'familia',difficulty:5},
    {word:'prejuicio',meaning:'偏见',phonetic:'/pɾe.ˈxwi.θjo/',category:'familia',difficulty:5},
    {word:'estereotipo',meaning:'刻板印象',phonetic:'/es.te.re.o.ˈti.po/',category:'familia',difficulty:5},
    {word:'convención',meaning:'惯例',phonetic:'/kom.ben.ˈθjon/',category:'familia',difficulty:5},
    {word:'usanza',meaning:'习俗',phonetic:'/u.ˈsan.θa/',category:'familia',difficulty:5},
    {word:'folclore',meaning:'民间传说',phonetic:'/fol.ˈklo.ɾe/',category:'familia',difficulty:5},
    {word:'mitología',meaning:'神话学',phonetic:'/mi.to.lo.ˈxi.a/',category:'familia',difficulty:5},
    {word:'ritual',meaning:'仪式',phonetic:'/ri.ˈtwal/',category:'familia',difficulty:5},
    {word:'ceremonia',meaning:'典礼',phonetic:'/θe.ɾe.ˈmo.nja/',category:'familia',difficulty:5},
    {word:'inauguración',meaning:'开幕式',phonetic:'/i.naw.ɣu.ra.ˈθjon/',category:'familia',difficulty:5},
    {word:'conmemoración',meaning:'纪念',phonetic:'/kon.me.mo.ra.ˈθjon/',category:'familia',difficulty:5},
    {word:'homenaje',meaning:'致敬',phonetic:'/o.me.ˈna.xe/',category:'familia',difficulty:5},
    {word:'legitimidad',meaning:'合法性',phonetic:'/le.xi.ti.mi.ˈðað/',category:'familia',difficulty:5},
    {word:'hegemonía',meaning:'霸权',phonetic:'/e.xe.mo.ˈni.a/',category:'familia',difficulty:5},
    {word:'soberanía',meaning:'主权',phonetic:'/so.be.ɾa.ˈni.a/',category:'familia',difficulty:5},

    // --- C1: 高级习语与固定搭配 (advanced idioms & collocations) ---
    {word:'a regañadientes',meaning:'勉强地',phonetic:'/a re.ɣa.ɲa.ˈðjen.tes/',category:'comida',difficulty:5},
    {word:'de buenas a primeras',meaning:'突然',phonetic:'/de ˈbwe.nas a pɾi.ˈme.ɾas/',category:'comida',difficulty:5},
    {word:'en un santiamén',meaning:'一瞬间',phonetic:'/en un san.tja.ˈmen/',category:'comida',difficulty:5},
    {word:'a pies juntillas',meaning:'坚信不疑',phonetic:'/a ˈpjes xun.ˈti.ʎas/',category:'comida',difficulty:5},
    {word:'de puntillas',meaning:'蹑手蹑脚',phonetic:'/de pun.ˈti.ʎas/',category:'comida',difficulty:5},
    {word:'a voces',meaning:'大声地',phonetic:'/a ˈbo.ses/',category:'comida',difficulty:5},
    {word:'sin ambages',meaning:'直截了当',phonetic:'/sin am.ˈba.xes/',category:'comida',difficulty:5},
    {word:'a tontas y a ciegas',meaning:'盲目地',phonetic:'/a ˈton.taz i a ˈθje.ɣas/',category:'comida',difficulty:5},
    {word:'de BRAZO caído',meaning:'消极怠工',phonetic:'/de ˈbɾa.θo ka.ˈi.ðo/',category:'comida',difficulty:5},
    {word:'por todo lo alto',meaning:'隆重地',phonetic:'/poɾ ˈto.lo lo ˈal.to/',category:'comida',difficulty:5},
    {word:'a la chita callando',meaning:'悄悄地',phonetic:'/a la ˈtʃi.ta ka.ˈʎan.do/',category:'comida',difficulty:5},
    {word:'a fuego lento',meaning:'慢火炖',phonetic:'/a ˈfwe.ɣo ˈlen.to/',category:'comida',difficulty:5},
    {word:'sin venir a cuento',meaning:'文不对题',phonetic:'/sin be.ˈniɾ a ˈkwen.to/',category:'comida',difficulty:5},
    {word:'de cuyo nombre no quiero acordarme',meaning:'不愿提及',phonetic:'/de ˈku.xo ˈnom.bɾe no ˈkje.ɾo a.koɾ.ˈðaɾ.me/',category:'comida',difficulty:5},
    {word:'ni por asomo',meaning:'绝不',phonetic:'/ni poɾ a.ˈso.mo/',category:'comida',difficulty:5},
    {word:'a bote pronto',meaning:'突然/不假思索',phonetic:'/a ˈbo.te ˈpɾon.to/',category:'comida',difficulty:5},
    {word:'con las manos en la masa',meaning:'当场抓获',phonetic:'/kon las ˈma.nos en la ˈma.sa/',category:'comida',difficulty:5},
    {word:'por si las moscas',meaning:'以防万一',phonetic:'/poɾ si las ˈmos.kas/',category:'comida',difficulty:5},
    {word:'a rajatabla',meaning:'严格地',phonetic:'/a ra.xa.ˈta.bla/',category:'comida',difficulty:5},
    {word:'hacer la vista gorda',meaning:'视而不见',phonetic:'/a.ˈθeɾ la ˈbis.ta ˈɣoɾ.ða/',category:'comida',difficulty:5},

    // --- C1: 高级学术与科学 (advanced academic & science) ---
    {word:'epistemológico',meaning:'认识论的',phonetic:'/e.pis.te.mo.ˈlo.xi.ko/',category:'cuerpo',difficulty:5},
    {word:'heurístico',meaning:'启发式的',phonetic:'/ew.ˈɾis.ti.ko/',category:'cuerpo',difficulty:5},
    {word:'taxonomía',meaning:'分类学',phonetic:'/tak.so.no.ˈmi.a/',category:'cuerpo',difficulty:5},
    {word:'corolario',meaning:'推论',phonetic:'/ko.ro.ˈla.rjo/',category:'cuerpo',difficulty:5},
    {word:'postulado',meaning:'公设',phonetic:'/pos.tu.ˈla.ðo/',category:'cuerpo',difficulty:5},
    {word:'teorema',meaning:'定理',phonetic:'/te.o.ˈɾe.ma/',category:'cuerpo',difficulty:5},
    {word:'axioma',meaning:'公理',phonetic:'/ak.ˈsjo.ma/',category:'cuerpo',difficulty:5},
    {word:'empirismo',meaning:'经验主义',phonetic:'/em.pi.ˈɾis.mo/',category:'cuerpo',difficulty:5},
    {word:'racionalismo',meaning:'理性主义',phonetic:'/ra.θjo.na.ˈlis.mo/',category:'cuerpo',difficulty:5},
    {word:'positivismo',meaning:'实证主义',phonetic:'/po.si.ti.ˈβis.mo/',category:'cuerpo',difficulty:5},
    {word:'reduccionismo',meaning:'简化论',phonetic:'/re.ðuk.θjo.ˈnis.mo/',category:'cuerpo',difficulty:5},
    {word:'determinismo',meaning:'决定论',phonetic:'/de.teɾ.mi.ˈnis.mo/',category:'cuerpo',difficulty:5},
    {word:'probabilista',meaning:'概率的',phonetic:'/pɾo.ba.bi.li.ˈsta/',category:'cuerpo',difficulty:5},
    {word:'inferencia',meaning:'推理',phonetic:'/in.fe.ˈɾen.θja/',category:'cuerpo',difficulty:5},
    {word:'conjetura',meaning:'猜想',phonetic:'/kon.xe.ˈtu.ɾa/',category:'cuerpo',difficulty:5},
    {word:'especulación',meaning:'推测',phonetic:'/es.pe.ku.la.ˈθjon/',category:'cuerpo',difficulty:5},
    {word:'comprobación',meaning:'验证',phonetic:'/kom.pro.ba.ˈθjon/',category:'cuerpo',difficulty:5},
    {word:'falsación',meaning:'证伪',phonetic:'/fal.sa.ˈθjon/',category:'cuerpo',difficulty:5},
    {word:'replicación',meaning:'复现',phonetic:'/re.pli.ka.ˈθjon/',category:'cuerpo',difficulty:5},
    {word:'variable',meaning:'变量',phonetic:'/ba.ˈrja.ble/',category:'cuerpo',difficulty:5}
  ]
};
